"""empty message

Revision ID: efcaaf55d111
Revises: 25e2b88e2efd
Create Date: 2020-04-05 20:43:26.960108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcaaf55d111'
down_revision = '25e2b88e2efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'image_link')
    # ### end Alembic commands ###
